=== AndrewHankewycz/WebApps_Lab11/Schedule/schedule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://127.0.0.1:8080"
	xmlns="http://127.0.0.1:8080"
	elementFormDefault="qualified">

<xs:simpleType name="stringType">
	<xs:restriction base="xs:string"/>
</xs:simpleType>

<xs:simpleType name="intType">
	<xs:restriction base="xs:positiveInteger"/>
</xs:simpleType>

<xs:simpleType name="weekDayType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="M"/>
        <xs:enumeration value="T"/>
        <xs:enumeration value="W"/>
        <xs:enumeration value="TH"/>
        <xs:enumeration value="F"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="dayIntType">
    <xs:restriction base="xs:positiveInteger">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="31"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="monthType">
    <xs:restriction base="xs:positiveInteger">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="12"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="dateType">
	<xs:sequence>
		<xs:element name="WeekDay" type="stringType"/>
		<xs:element name="Month" type="stringType"/>
		<xs:element name="Day" type="stringType"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="labType">
    <xs:sequence>
	<xs:element name="Topic" type="stringType"/>
	<xs:element name="Project" type="stringType"/>
	<xs:element name="Notes" type="stringType"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="tagType">
    <xs:sequence>
    <xs:element name="ClassNum" type="intType"/>
    <xs:element name="Date" type="dateType"/>
    <xs:element name="Tag" type="stringType"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="rowType">
    <xs:sequence>
    <xs:element name="TopicTag" type="tagType"/>
    <xs:element name="Lab" type="labType"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="rowType1">
    <xs:sequence>
    <xs:element name="TopicTag" type="tagType"/>
    <xs:element name="NonLab" type="labType"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="rowType2">
    <xs:sequence>
    <xs:element name="AltTopicTag" type="tagType"/>
    <xs:element name="NonLab" type="labType"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="rowType3">
    <xs:sequence>
    <xs:element name="AltTopicTag" type="tagType"/>
    <xs:element name="Lab" type="labType"/>    
    </xs:sequence>
</xs:complexType>

<xs:complexType name="rowType4">
    <xs:sequence>
    <xs:element name="TopicTag" type="tagType"/>
    <xs:element name="Presentation" type="stringType"/>    
    </xs:sequence>
</xs:complexType>

<xs:complexType name="headerType">
    <xs:sequence>
    <xs:element name="ClassH" type="stringType"/>
    <xs:element name="DateH" type="stringType"/>
    <xs:element name="TagH" type="stringType"/>  
    <xs:element name="TopicH" type="stringType"/>
    <xs:element name="ProjectH" type="stringType"/> 
    <xs:element name="NotesH" type="stringType"/>
    </xs:sequence>
</xs:complexType>

<xs:element name="Row" type="rowType1"/>
<xs:element name="HeaderH" type="headerType"/>

</xs:schema>

=== AndrewHankewycz/WebApps_Lab11/Schedule/schedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<Row xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schedule.xsd">
	<ClassNum>1</ClassNum>
	<Date>
            <Day>M</Day>
            <Month>1</Month>
            <Year>2012</Year>
        </Date>
        <Tag>JSON</Tag>
        <Project>Project One</Project>
        <Topic>Coding in Javascript</Topic>
        <Notes>These are some notes</Notes>
</Row>
